"""Executable actions generated by AI planning."""

from dataclasses import dataclass


@dataclass
class Action:
    action: str
    command: str = ""
    reason: str = ""
    risk: str = "unknown"

    def to_dict(self):
        return self.__dict__
